site_name: 'NCBI Mass Sequence Downloader manual'
site_favicon: 'assets/Icon.png'
pages:
    - 'Introduction': 'index.md'
    - 'Installation': 'install.md'
    - 'Binary builds': 'binaries.md'
    - 'Usage': 'usage.md'
    - 'Testing': 'testing.md'
    - 'Future Plans': 'future.md'
    - 'Limitations': 'limits.md'
